/**
 * Generated by Gas3 v3.1.0 (Granite Data Services).
 *
 * NOTE: this file is only generated if it does not exist. You may safely put
 * your custom code here.
 */

package democustomer {

    [RemoteClass(alias="democustomer.CustomerService")]
    public class CustomerService extends CustomerServiceBase {

        public function CustomerService() {
            super();
        }
    }
}
