/**
 * Generated by Gas3 v3.1.0 (Granite Data Services).
 *
 * NOTE: this file is only generated if it does not exist. You may safely put
 * your custom code here.
 */

package democustomer {

    [Bindable]
    [RemoteClass(alias="democustomer.PersonAuthority")]
    public class PersonAuthority extends PersonAuthorityBase {

        public function PersonAuthority() {
            super();
        } 
    }
}